name: dexart_toilet_image

task_name: toilet


image_shape: &image_shape [3, 84, 84]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    image:
      shape: *image_shape
      type: rgb
    agent_pos:
      shape: [32]
      type: low_dim
  action:
    shape: [22]

env_runner:
  _target_: diffusion_policy_3d.env_runner.dexart_image_runner.DexArtImageRunner
  n_train: 20
  train_start_seed: 0
  n_test: 20
  test_start_seed: 100000
  max_steps: 50
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  n_envs: null
  task_name: toilet

dataset:
  _target_: diffusion_policy_3d.dataset.dexart_image_dataset.DexArtImageDataset
  zarr_path: data/dexart_toilet_expert.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
